namespace FilmSerileri.Services;

public class LocalizationService : ILocalizationService
{
  private readonly ISettingsService _settingsService;

  private static readonly Dictionary<string, BilingualUi> Strings = new()
  {
    ["site_name"] = new("Sinema Serileri", "Cinema Series"),
    ["nav_home"] = new("Ana Sayfa", "Home"),
    ["nav_settings"] = new("Ayarlar", "Settings"),
    ["footer_tagline"] = new("Efsanevi film serilerini keşfedin.", "Discover legendary movie franchises."),
    ["featured_badge"] = new("Öne Çıkan Seri", "Featured Series"),
    ["explore_series"] = new("Seriyi Keşfet", "Explore Series"),
    ["all_series"] = new("Tüm Seriler", "All Series"),
    ["all_series_desc"] = new("En sevilen film serilerini, oyuncu kadrolarını ve film listelerini inceleyin.", "Browse beloved franchises, cast lists, and filmographies."),
    ["favorite"] = new("Favori", "Favorite"),
    ["films"] = new("film", "films"),
    ["stat_series"] = new("Film Serisi", "Franchises"),
    ["stat_movies"] = new("Toplam Film", "Total Films"),
    ["stat_cast"] = new("Oyuncu Profili", "Cast Profiles"),
    ["back_home"] = new("Ana Sayfa", "Home"),
    ["about"] = new("Hakkında", "About"),
    ["director"] = new("Yönetmen", "Director"),
    ["studio"] = new("Stüdyo", "Studio"),
    ["movie_count"] = new("Film Sayısı", "Film Count"),
    ["movies_section"] = new("Filmler", "Films"),
    ["cast_section"] = new("Oyuncu Kadrosu", "Cast"),
    ["theme_music"] = new("Film Müziği", "Theme Music"),
    ["theme_music_play"] = new("Müziği Başlat", "Play Theme"),
    ["theme_music_pause"] = new("Duraklat", "Pause"),
    ["theme_music_playing"] = new("Çalıyor", "Playing"),
    ["minutes"] = new("dk", "min"),
    ["settings_title"] = new("Ayarlar", "Settings"),
    ["settings_desc"] = new("Site deneyimini kişiselleştirin.", "Personalize your browsing experience."),
    ["settings_saved"] = new("Ayarlarınız kaydedildi!", "Your settings have been saved!"),
    ["appearance"] = new("Görünüm", "Appearance"),
    ["theme"] = new("Tema", "Theme"),
    ["theme_dark"] = new("Koyu Tema", "Dark Theme"),
    ["theme_light"] = new("Açık Tema", "Light Theme"),
    ["compact_view"] = new("Kompakt Görünüm", "Compact View"),
    ["show_ratings"] = new("IMDb Puanlarını Göster", "Show IMDb Ratings"),
    ["preferences"] = new("Tercihler", "Preferences"),
    ["favorite_series"] = new("Favori Seri", "Favorite Series"),
    ["favorite_hint"] = new("Favori seriniz ana sayfada ilk sırada gösterilir.", "Your favorite franchise appears first on the home page."),
    ["language"] = new("Dil", "Language"),
    ["lang_tr"] = new("Türkçe", "Turkish"),
    ["lang_en"] = new("English", "English"),
    ["select_none"] = new("Seçiniz (yok)", "None"),
    ["save"] = new("Kaydet", "Save"),
    ["search_placeholder"] = new("Seri, oyuncu veya tür ara...", "Search series, actor, or genre..."),
    ["filter_genre"] = new("Tür", "Genre"),
    ["filter_all_genres"] = new("Tüm Türler", "All Genres"),
    ["filter_min_rating"] = new("Min. Puan", "Min. Rating"),
    ["filter_any_rating"] = new("Tümü", "Any"),
    ["filter_sort"] = new("Sırala", "Sort"),
    ["sort_rating"] = new("Puana Göre", "By Rating"),
    ["sort_year"] = new("Yıla Göre", "By Year"),
    ["sort_title"] = new("İsme Göre", "By Title"),
    ["sort_movies"] = new("Film Sayısına Göre", "By Film Count"),
    ["search_results"] = new("sonuç bulundu", "results found"),
    ["no_results"] = new("Aramanızla eşleşen seri bulunamadı.", "No series match your search."),
    ["clear_filters"] = new("Filtreleri Temizle", "Clear Filters"),
    ["role_lead"] = new("Başrol", "Lead"),
    ["role_supporting"] = new("Yardımcı Rol", "Supporting"),
    ["role_antagonist"] = new("Antagonist", "Antagonist"),
    ["home_title"] = new("Ana Sayfa", "Home"),
    ["nav_actors"] = new("Oyuncular", "Actors"),
    ["nav_compare"] = new("Karşılaştır", "Compare"),
    ["nav_universe"] = new("Evrenler", "Universes"),
    ["nav_library"] = new("Kütüphanem", "My Library"),
    ["nav_login"] = new("Giriş", "Login"),
    ["nav_logout"] = new("Çıkış", "Logout"),
    ["nav_register"] = new("Kayıt Ol", "Register"),
    ["nav_api"] = new("API", "API"),
    ["random_series"] = new("Rastgele Seri", "Random Series"),
    ["similar_series"] = new("Benzer Seriler", "Similar Series"),
    ["watch_trailer"] = new("Fragmanı İzle", "Watch Trailer"),
    ["timeline"] = new("Kronoloji", "Timeline"),
    ["compare_title"] = new("Seri Karşılaştırma", "Compare Franchises"),
    ["compare_desc"] = new("İki film serisini yan yana karşılaştırın.", "Compare two franchises side by side."),
    ["compare_select_a"] = new("Seri A", "Series A"),
    ["compare_select_b"] = new("Seri B", "Series B"),
    ["compare_btn"] = new("Karşılaştır", "Compare"),
    ["actors_title"] = new("Oyuncular", "Cast"),
    ["actors_desc"] = new("Tüm serilerdeki oyuncu profilleri.", "Cast profiles across all franchises."),
    ["actor_roles"] = new("Rolleri", "Roles"),
    ["universe_title"] = new("Evren Haritaları", "Universe Maps"),
    ["universe_desc"] = new("Star Wars, Orta Dünya ve MCU evrenlerini keşfedin.", "Explore Star Wars, Middle-earth, and MCU timelines."),
    ["library_title"] = new("Kütüphanem", "My Library"),
    ["watchlist"] = new("İzleme Listesi", "Watchlist"),
    ["watched"] = new("İzlediklerim", "Watched"),
    ["notes"] = new("Notlarım", "Notes"),
    ["add_watchlist"] = new("Listeye Ekle", "Add to Watchlist"),
    ["remove_watchlist"] = new("Listeden Çıkar", "Remove from Watchlist"),
    ["mark_watched"] = new("İzledim", "Mark Watched"),
    ["save_note"] = new("Notu Kaydet", "Save Note"),
    ["page_prev"] = new("Önceki", "Previous"),
    ["page_next"] = new("Sonraki", "Next"),
    ["loading"] = new("Yükleniyor...", "Loading..."),
    ["install_app"] = new("Uygulamayı Yükle", "Install App"),
    ["login_title"] = new("Giriş Yap", "Sign In"),
    ["register_title"] = new("Hesap Oluştur", "Create Account"),
    ["email"] = new("E-posta", "Email"),
    ["password"] = new("Şifre", "Password"),
    ["display_name"] = new("Görünen Ad", "Display Name"),
    ["nav_dashboard"] = new("İstatistikler", "Stats"),
    ["nav_admin"] = new("Yönetim", "Admin"),
    ["dashboard_title"] = new("İstatistik Paneli", "Statistics Dashboard"),
    ["dashboard_desc"] = new("Katalogdaki serilerin sayısal görünümü.", "A numeric overview of the catalog."),
    ["dash_series"] = new("Seri", "Series"),
    ["dash_movies"] = new("Film", "Movies"),
    ["dash_actors"] = new("Oyuncu", "Actors"),
    ["dash_avg_rating"] = new("Ortalama IMDb", "Average IMDb"),
    ["chart_genres"] = new("Tür Dağılımı", "Genre Distribution"),
    ["chart_decades"] = new("On Yıllara Göre Filmler", "Films by Decade"),
    ["chart_top"] = new("En Yüksek Puanlı Seriler", "Top Rated Series"),
    ["reviews_title"] = new("Kullanıcı Yorumları", "User Reviews"),
    ["review_yours"] = new("Senin Değerlendirmen", "Your Review"),
    ["review_placeholder"] = new("Bu seri hakkında ne düşünüyorsun?", "What do you think about this franchise?"),
    ["review_submit"] = new("Yorumu Kaydet", "Save Review"),
    ["review_delete"] = new("Yorumu Sil", "Delete Review"),
    ["review_login"] = new("Yorum yapmak için giriş yapın →", "Sign in to write a review →"),
    ["review_empty"] = new("Henüz yorum yok. İlk yorumu sen yaz!", "No reviews yet. Be the first!"),
    ["recommended_title"] = new("Sana Özel Öneriler", "Recommended for You"),
    ["recommended_desc"] = new("Kütüphanene göre seçildi.", "Picked based on your library."),
    ["admin_title"] = new("İçerik Yönetimi", "Content Management"),
    ["admin_new"] = new("Yeni Seri", "New Series"),
    ["admin_edit"] = new("Düzenle", "Edit"),
    ["admin_save"] = new("Kaydet", "Save"),
    ["admin_cancel"] = new("Vazgeç", "Cancel"),
    ["admin_delete"] = new("Sil", "Delete"),
    ["admin_delete_confirm"] = new("Bu seri kalıcı olarak silinecek. Emin misin?", "This series will be permanently deleted. Are you sure?"),
    ["admin_col_title"] = new("Başlık", "Title"),
    ["admin_col_movies"] = new("Film Sayısı", "Movies"),
    ["admin_section_general"] = new("Genel Bilgiler", "General Info"),
    ["admin_section_desc"] = new("Açıklama", "Description"),
    ["admin_section_movies"] = new("Filmler", "Movies"),
    ["admin_section_cast"] = new("Oyuncular", "Cast"),
    ["admin_add_movie"] = new("Film Ekle", "Add Movie"),
    ["admin_add_cast"] = new("Oyuncu Ekle", "Add Cast Member"),
    ["nav_profile"] = new("Profilim", "Profile"),
    ["nav_quiz"] = new("Quiz", "Quiz"),
    ["profile_title"] = new("Profilim", "My Profile"),
    ["profile_member_since"] = new("Üyelik", "Member since"),
    ["profile_genres"] = new("Keşfedilen Tür", "Genres Explored"),
    ["profile_quiz_best"] = new("En İyi Quiz", "Best Quiz"),
    ["badges_title"] = new("Rozetler", "Badges"),
    ["badge_first_step"] = new("İlk Adım", "First Step"),
    ["badge_first_step_desc"] = new("İlk seriyi izledin", "Watched your first series"),
    ["badge_marathon"] = new("Maratoncu", "Marathoner"),
    ["badge_marathon_desc"] = new("3 seri izledin", "Watched 3 series"),
    ["badge_cinephile"] = new("Sinefil", "Cinephile"),
    ["badge_cinephile_desc"] = new("7 seri izledin", "Watched 7 series"),
    ["badge_first_review"] = new("İlk Yorum", "First Review"),
    ["badge_first_review_desc"] = new("İlk yorumunu yazdın", "Wrote your first review"),
    ["badge_critic"] = new("Eleştirmen", "Critic"),
    ["badge_critic_desc"] = new("5 yorum yazdın", "Wrote 5 reviews"),
    ["badge_collector"] = new("Koleksiyoncu", "Collector"),
    ["badge_collector_desc"] = new("Listene 5 seri ekledin", "Added 5 series to watchlist"),
    ["badge_explorer"] = new("Kâşif", "Explorer"),
    ["badge_explorer_desc"] = new("4 farklı tür keşfettin", "Explored 4 different genres"),
    ["badge_quiz_master"] = new("Quiz Ustası", "Quiz Master"),
    ["badge_quiz_master_desc"] = new("Quizde 8+ doğru yaptın", "Scored 8+ on the quiz"),
    ["palette_placeholder"] = new("Seri, film veya oyuncu ara...", "Search series, movies, actors..."),
    ["palette_no_results"] = new("Sonuç bulunamadı", "No results found"),
    ["palette_nav"] = new("gezin", "navigate"),
    ["palette_open"] = new("aç", "open"),
    ["quiz_title"] = new("Film Quizi", "Movie Quiz"),
    ["quiz_desc"] = new("Film serisi bilgini test et!", "Test your franchise knowledge!"),
    ["quiz_intro"] = new("10 soru, 4 şık. Hazır mısın?", "10 questions, 4 choices. Ready?"),
    ["quiz_start"] = new("Başla", "Start"),
    ["quiz_score"] = new("Skor", "Score"),
    ["quiz_final"] = new("Sonuç", "Result"),
    ["quiz_play_again"] = new("Tekrar Oyna", "Play Again"),
    ["quiz_leaderboard"] = new("Skor Tablosu", "Leaderboard"),
    ["quiz_lb_empty"] = new("Henüz skor yok. İlk sen ol!", "No scores yet. Be the first!"),
    ["quiz_saved"] = new("Skorun kaydedildi!", "Your score was saved!"),
    ["quiz_login_to_save"] = new("Skorunu kaydetmek için giriş yap.", "Sign in to save your score."),
    ["quiz_q_actor"] = new("{1} serisinde {0} karakterini kim oynadı?", "Who played {0} in {1}?"),
    ["quiz_q_year"] = new("\"{0}\" filmi hangi yıl vizyona girdi?", "In which year was \"{0}\" released?"),
    ["quiz_q_series"] = new("\"{0}\" filmi hangi seriye ait?", "Which franchise does \"{0}\" belong to?"),
    ["quiz_q_director"] = new("{0} serisinin yönetmeni kim?", "Who directed {0}?"),
    ["forgot_password"] = new("Şifremi Unuttum", "Forgot Password"),
    ["forgot_password_desc"] = new("E-posta adresini gir, sana sıfırlama bağlantısı gönderelim.", "Enter your email and we'll send you a reset link."),
    ["send_reset_link"] = new("Sıfırlama Bağlantısı Gönder", "Send Reset Link"),
    ["reset_password"] = new("Şifreyi Sıfırla", "Reset Password"),
    ["new_password"] = new("Yeni Şifre", "New Password"),
    ["confirm_password"] = new("Şifre (Tekrar)", "Confirm Password"),
    ["reset_sent"] = new("Hesap varsa sıfırlama bağlantısı gönderildi. (Dev ortamında bağlantı uygulama loguna yazılır.)", "If the account exists, a reset link was sent. (In dev, the link is written to the app log.)"),
    ["reset_done"] = new("Şifren güncellendi. Giriş yapabilirsin.", "Your password was updated. You can sign in."),
    ["admin_reviews"] = new("Yorum Moderasyonu", "Review Moderation"),
    ["admin_col_author"] = new("Yazar", "Author"),
    ["admin_col_rating"] = new("Puan", "Rating"),
    ["admin_col_text"] = new("Yorum", "Review"),
    ["admin_col_date"] = new("Tarih", "Date"),
  };

  public LocalizationService(ISettingsService settingsService)
  {
    _settingsService = settingsService;
  }

  public string CurrentLanguage => _settingsService.GetSettings().Language;

  public string T(string key, string? language = null)
  {
    var lang = language ?? CurrentLanguage;
    return Strings.TryGetValue(key, out var text) ? text.Get(lang) : key;
  }

  private record BilingualUi(string Tr, string En)
  {
    public string Get(string lang) =>
      lang.Equals("en", StringComparison.OrdinalIgnoreCase) ? En : Tr;
  }
}
